################################# Default configuration ###################
baseURL = "https://www.wisslmedia.com"
title = "WisslMedia"
theme = "meghna"
# post pagination
[pagination]
  pagerSize = 6

# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
# disableLanguages = ["en-us"]
defaultContentLanguage = "fr"

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/animate-css/animate.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"

# js plugins
[[params.plugins.js]]
URL = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
URL = "plugins/wow/wow.min.js"

############################# Navigation ##################################
[menu]

  [[menu.main]]
  name = "Gamifiez"
  URL = "gamifiez"
  weight = 1

  [[menu.main]]
  name = "Data/CRM"
  URL = "data_crm"
  weight = 2

  [[menu.main]]
  name = "Monétisez"
  URL = "monetize"
  weight = 3

  [[menu.main]]
  name = "PACKS"
  URL = "feature"
  weight = 4

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 6  
  
  [[menu.main]]
  name = "DÉMANDER UNE DÉMO"
  URL = "contact"
  weight = 7



############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Gamifiez, boostez l’engagement et monétisez votre audience"
author = "WisslMedia"
# Google Analitycs
googleAnalitycsID = "UA-90139151-8"
# post share
postShare = true

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

############################# social icons ##########################
##[[params.social_Icon]]
##icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
##link = "#"

[[params.social_Icon]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/WisslMedia"

##[[params.social_Icon]]
##icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
##link = "#"

[[params.social_Icon]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/wissl-media/"

[[params.social_Icon]]
icon = "ti-instagram"
link = "https://www.instagram.com/wisslmedia/"

##[[params.social_Icon]]
##icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
##link = "#"

################################# language ################################
[languages]

  ################################ English Language ########################
  #[Languages.en]
  #languageName = "En"
  #languageCode = "en-us"
  #contentDir = "content/english"
  #weight = 2
  #home = "Home"

  ################################ France Language ########################
  [languages.fr]
  languageName = "Fr"
  languageCode = "fr-fr"
  contentDir = "content/french"
  weight = 1
  home = "Accueil"